on: push
name: Build & Release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          go-version: '1.21'
      - name: build
        run: |
          ./build.sh && ls bin/
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: bin/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}