on: push
name: Build & Release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          go-version: '1.21.0'
      - name: build
        run: |
          ./build.sh
  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@master
      - name: Create release
        uses: Roang-zero1/github-create-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload release artifacts
        uses: Roang-zero1/github-upload-release-artifacts-action@v2
        with:
          args: "bin mql"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}